<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Title>$(AssemblyName)</Title>
    <Version>2.0.1</Version>
    <Authors>Jay9011</Authors>
    <Company>SECUiDEA</Company>
    <Description>한글 가상 키보드 지원</Description>
    <Copyright>Jay9011</Copyright>
    <PackageReadmeFile>ReadMe.md</PackageReadmeFile>
    <RepositoryUrl>http://192.168.0.39/VirtualKeyboard.Input.Korean.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReleaseNotes>천지인 조합 추가 (복합 종성 대기 기능 추가)</PackageReleaseNotes>
    <AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
    <FileVersion>$(VersionPrefix)</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Composer\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="VirtualKeyboard.Input" Version="1.0.4" />
  </ItemGroup>

  <ItemGroup>
    <None Include="ReadMe.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

	<Target Name="PushNuGetPackage" AfterTargets="Pack">
		<Exec Command="dotnet nuget push $(PackageOutputPath)$(AssemblyName).$(Version).nupkg --source Local" />
	</Target>

</Project>
